version: '3.8'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./models/news:/usr/src/models
      - ./pipelines/train/data:/usr/src/train-data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./models/deploy:/usr/src/model
    ports:
      - 8000:8000
